POST http://localhost:4000/Register
Content-Type: application/json

{
    "fullname":"Chadichihi",
    "email":"Admin@mail.com",
    "phonenumber":"123456789",
    "password":"1111",
    "role":"Admin",
    "company":"Atlas",
    "BirthDate":"02/10/1993"
}

###

POST  http://localhost:4000/LogIn
Content-Type: application/json

{
    "email":"Admin@mail.com",
    "password":"1111"
}